# **Functions**

**1. Read**

In [ ]:
import pandas as pd
import os
df = pd.read_csv(r'/content/sample_data/test.csv')

**2. head()**

In [ ]:
import pandas as pd
import os
df = pd.read_csv(r'/content/sample_data/test.csv')
df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

**3. tail()**

In [ ]:
import pandas as pd
import os
df = pd.read_csv(r'/content/sample_data/test.csv')
df.tail()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

**Shape** *(key word.)*

In [ ]:
import pandas as pd
import os
df = pd.read_csv(r'/content/sample_data/test.csv')
df.shape

(418, 11)

**4. info()**

In [ ]:
import pandas as pd
import os
df = pd.read_csv(r'/content/sample_data/test.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB

**5. to_datetime()**

In [ ]:
import pandas as pd
import os
import datetime as dt
df = pd.read_csv(r'/content/sample_data/test.csv')
# f['stop_date'] = pd.to_datetime(df['stop_date'])
# df['stop_time'] = pd.to_datetime(df['stop_time'], format = "%H:%M").dt.time

**6. isnull() and sum()**

In [ ]:
import pandas as pd
import os
df.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

**7. drop()**

In [ ]:
import pandas as pd
import os
df = pd.read_csv(r'/content/sample_data/test.csv')
df.drop(['Cabin'], axis = 1, inplace = True)
df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,S

**8. describe()**

In [ ]:
import pandas as pd
import os
df = pd.read_csv(r'/content/sample_data/test.csv')
df.describe()

       PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.841838   14.181209    0.896760    0.981429   55.907576
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

**9. value_count()**

In [ ]:
import pandas as pd
import os
df = pd.read_csv(r'/content/sample_data/test.csv')
df['Cabin'].value_counts()

B57 B59 B63 B66    3
B45                2
C89                2
C55 C57            2
A34                2
                  ..
E52                1
D30                1
E31                1
C62 C64            1
C105               1
Name: Cabin, Length: 76, dtype: int64

**isnull() and sum() for a particular column.**

In [ ]:
import pandas as pd
import os
df = pd.read_csv(r'/content/sample_data/test.csv')
df['Age'].isnull().sum()

86

**10. fillna()**

In [ ]:
import pandas as pd
import os
df = pd.read_csv(r'/content/sample_data/test.csv')
df['Age'].fillna(df['Age'].mode,inplace=True)
df['Age'].isnull().sum()

0

**11. sample()**

In [ ]:
import pandas as pd
import os
df = pd.read_csv(r'/content/sample_data/test.csv')
df.sample(7)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
150,1042,1,"Earnshaw, Mrs. Boulton (Olive Potter)",female,23.0,0,1,11767,83.1583,C54,C
82,974,1,"Case, Mr. Howard Brown",male,49.0,0,0,19924,26.0000,NaN,S
222,1114,2,"Cook, Mrs. (Selena Rogers)",female,22.0,0,0,W./C. 14266,10.5000,F33,S
374,1266,1,"Dodge, Mrs. Washington (Ruth Vidaver)",female,54.0,1,1,33638,81.8583,A34,S
90,982,3,"Dyker, Mrs. Adolf Fredrik (Anna Elisabeth Judi...",female,22.0,1,0,347072,13.9000,NaN,S
165,1057,3,"Kink-Heilmann, Mrs. Anton (Luise Heilmann)",female,26.0,1,1,315153,22.0250,NaN,S
70,962,3,"Mulvihill, Miss. Bertha E",female,24.0,0,0,382653,7.7500,NaN,Q

**12. nunique()**

In [ ]:
import pandas as pd
import os
df = pd.read_csv(r'/content/sample_data/test.csv')
df['Name'].nunique()

418

**13. columns**

In [ ]:
import pandas as pd
import os
df = pd.read_csv(r'/content/sample_data/test.csv')
df.columns

Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

**14. nsmallest() & nlargest()**

In [ ]:
import pandas as pd
import os
df = pd.read_csv(r'/content/sample_data/test.csv')
df.nlargest(4, "Age")

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
96,988,1,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.0,1,0,19877,78.8500,C46,S
81,973,1,"Straus, Mr. Isidor",male,67.0,1,0,PC 17483,221.7792,C55 C57,S
179,1071,1,"Compton, Mrs. Alexander Taylor (Mary Eliza Ing...",female,64.0,0,2,PC 17756,83.1583,E45,C
236,1128,1,"Warren, Mr. Frank Manley",male,64.0,1,0,110813,75.2500,D37,C

In [ ]:
df.nsmallest(4, "Age")

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
354,1246,3,"Dean, Miss. Elizabeth Gladys Millvina""""",female,0.17,1,2,C.A. 2315,20.575,NaN,S
201,1093,3,"Danbom, Master. Gilbert Sigvard Emanuel",male,0.33,0,2,347080,14.400,NaN,S
281,1173,3,"Peacock, Master. Alfred Edward",male,0.75,1,1,SOTON/O.Q. 3101315,13.775,NaN,S
307,1199,3,"Aks, Master. Philip Frank",male,0.83,0,1,392091,9.350,NaN,S

**15. groupby()**

In [ ]:
import pandas as pd
import os
import numpy as np
df = pd.read_csv(r'/content/sample_data/test.csv')
df.groupby('Pclass').agg(np.mean)

<ipython-input-95-1574bd02c8ac>:5: FutureWarning: The operation <function mean at 0x7fc5b0d83010> failed on a column. If any error is raised, this will raise an exception in a future version of pandas. Drop these columns to avoid this warning.
  df.groupby('Pclass').agg(np.mean)

        PassengerId        Age     SibSp     Parch       Fare
Pclass
1       1098.224299  40.918367  0.476636  0.383178  94.280297
2       1117.935484  28.777500  0.376344  0.344086  22.202104
3       1094.178899  24.027945  0.463303  0.417431  12.459678

**16. get_group()**

In [ ]:
import pandas as pd
import os
df = pd.read_csv(r'/content/sample_data/test.csv')
df.groupby('Pclass').get_group(1)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
11,903,1,"Jones, Mr. Charles Cresson",male,46.0,0,0,694,26.0000,NaN,S
12,904,1,"Snyder, Mrs. John Pillsbury (Nelle Stevenson)",female,23.0,1,0,21228,82.2667,B45,S
14,906,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.0,1,0,W.E.P. 5734,61.1750,E31,S
20,912,1,"Rothschild, Mr. Martin",male,55.0,1,0,PC 17603,59.4000,NaN,C
22,914,1,"Flegenheim, Mrs. Alfred (Antoinette)",female,NaN,0,0,PC 17598,31.6833,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
403,1295,1,"Carrau, Mr. Jose Pedro",male,17.0,0,0,113059,47.1000,NaN,S
404,1296,1,"Frauenthal, Mr. Isaac Gerald",male,43.0,1,0,17765,27.7208,D40,C
407,1299,1,"Widener, Mr. George Dunton",male,50.0,1,1,113503,211.5000,C80,C
411,1303,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,C78,Q
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C

**17. loc() & iloc()      
loc() = selecting by label     
iloc() = selecting by position**

In [ ]:
import pandas as pd
import os
df = pd.read_csv(r'/content/sample_data/test.csv')
df.loc[11:15,['Pclass','Name']]

    Pclass                                               Name
11       1                         Jones, Mr. Charles Cresson
12       1      Snyder, Mrs. John Pillsbury (Nelle Stevenson)
13       2                               Howard, Mr. Benjamin
14       1  Chaffee, Mrs. Herbert Fuller (Carrie Constance...
15       2      del Carlo, Mrs. Sebastiano (Argenia Genovesi)

**loc() with condition**

In [ ]:
import pandas as pd
import os
df = pd.read_csv(r'/content/sample_data/test.csv')
df.loc[(df.Age < 16) & (df.Pclass == 1)]

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
64,956,1,"Ryerson, Master. John Borie",male,13.0,2,2,PC 17608,262.375,B57 B59 B63 B66,C
196,1088,1,"Spedden, Master. Robert Douglas",male,6.0,0,2,16966,134.500,E34,C

In [ ]:
import pandas as pd
import os
df = pd.read_csv(r'/content/sample_data/test.csv')
df.loc[(df.Age == 18) & (df.Pclass == 2)]

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
238,1130,2,"Hiltunen, Miss. Marta",female,18.0,1,1,250650,13.0,NaN,S
340,1232,2,"Fillbrook, Mr. Joseph Charles",male,18.0,0,0,C.A. 15185,10.5,NaN,S
352,1244,2,"Dibden, Mr. William",male,18.0,0,0,S.O.C. 14879,73.5,NaN,S

In [ ]:
import pandas as pd
import os
df = pd.read_csv(r'/content/sample_data/test.csv')
df.iloc[69:70,:5]

    PassengerId  Pclass                                 Name     Sex   Age
69          961       1  Fortune, Mrs. Mark (Mary McDougald)  female  60.0

**18. sort()**

In [ ]:
import pandas as pd
import os
df = pd.read_csv(r'/content/sample_data/test.csv')
df.loc[(df.Age == 18) & (df.Pclass == 2)]
df[['Name','Pclass','Fare','Age']].sort_values(by = 'Name')

                                              Name  Pclass     Fare   Age
392                  Abbott, Master. Eugene Joseph       3  20.2500  13.0
345                    Abelseth, Miss. Karen Marie       3   7.6500  16.0
57                   Abelseth, Mr. Olaus Jorgensen       3   7.6500  25.0
251       Abrahamsson, Mr. Abraham August Johannes       3   7.9250  20.0
8        Abrahim, Mrs. Joseph (Sophie Halaut Easu)       3   7.2292  18.0
..                                             ...     ...      ...   ...
336                     de Brito, Mr. Jose Joaquim       2  13.0000  32.0
260           de Messemaeker, Mr. Guillaume Joseph       3  17.4000  36.5
15   del Carlo, Mrs. Sebastiano (Argenia Genovesi)       2  27.7208  24.0
344            van Billiard, Master. James William       3  14.5000   NaN
192              van Billiard, Master. Walter John       3  14.5000  11.5

[418 rows x 4 columns]

**19. query()**

In [ ]:
import pandas as pd
import os
df = pd.read_csv(r'/content/sample_data/test.csv')
df.query('18 < Age < 23').head(10)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
9,901,3,"Davies, Mr. John Samuel",male,21.0,2,0,A/4 48871,24.1500,NaN,S
17,909,3,"Assaf, Mr. Gerios",male,21.0,0,0,2692,7.2250,NaN,C
23,915,1,"Williams, Mr. Richard Norris II",male,21.0,0,1,PC 17597,61.3792,NaN,C
26,918,1,"Ostby, Miss. Helene Ragnhild",female,22.0,0,1,113509,61.9792,B36,C
27,919,3,"Daher, Mr. Shedid",male,22.5,0,0,2698,7.2250,NaN,C
35,927,3,"Katavelas, Mr. Vassilios (Catavelas Vassilios"")""",male,18.5,0,0,2682,7.2292,NaN,C
37,929,3,"Cacic, Miss. Manda",female,21.0,0,0,315087,8.6625,NaN,S
52,944,2,"Hocking, Miss. Ellen Nellie""""",female,20.0,2,1,29105,23.0000,NaN,S
63,955,3,"Bradley, Miss. Bridget Delia",female,22.0,0,0,334914,7.7250,NaN,Q

In [ ]:
import pandas as pd
import os
df = pd.read_csv(r'/content/sample_data/test.csv')
df.query('18 < Age < 21 and Sex == "female"')

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
52,944,2,"Hocking, Miss. Ellen Nellie""""",female,20.0,2,1,29105,23.0000,NaN,S
98,990,3,"Braf, Miss. Elin Ester Maria",female,20.0,0,0,347471,7.8542,NaN,S
113,1005,3,"Buckley, Miss. Katherine",female,18.5,0,0,329944,7.2833,NaN,Q
176,1068,2,"Sincock, Miss. Maude",female,20.0,0,0,C.A. 33112,36.7500,NaN,S
258,1150,2,"Bentham, Miss. Lilian W",female,19.0,0,0,28404,13.0000,NaN,S
275,1167,2,"Bryhl, Miss. Dagmar Jenny Ingeborg",female,20.0,1,0,236853,26.0000,NaN,S
333,1225,3,"Nakid, Mrs. Said (Waika Mary"" Mowad)""",female,19.0,1,1,2653,15.7417,NaN,C
383,1275,3,"McNamee, Mrs. Neal (Eileen O'Leary)",female,19.0,1,0,376566,16.1000,NaN,S

In [ ]:
df.query('18 < Age < 21 and Sex == "male"')

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
35,927,3,"Katavelas, Mr. Vassilios (Catavelas Vassilios"")""",male,18.5,0,0,2682,7.2292,NaN,C
109,1001,2,"Swane, Mr. George",male,18.5,0,0,248734,13.0000,F,S
235,1127,3,"Vendel, Mr. Olof Edvin",male,20.0,0,0,350416,7.8542,NaN,S
237,1129,3,"Baccos, Mr. Raffull",male,20.0,0,0,2679,7.2250,NaN,C
251,1143,3,"Abrahamsson, Mr. Abraham August Johannes",male,20.0,0,0,SOTON/O2 3101284,7.9250,NaN,S
317,1209,2,"Rogers, Mr. Reginald Harry",male,19.0,0,0,28004,10.5000,NaN,S
405,1297,2,"Nourney, Mr. Alfred (Baron von Drachstedt"")""",male,20.0,0,0,SC/PARIS 2166,13.8625,D38,C

**20. set_index()**

In [ ]:
import pandas as pd
import os
df = pd.read_csv(r'/content/sample_data/test.csv')
df.set_index('Pclass').head()

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Pclass,,,,,,,,,,
3,892,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
3,893,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
3,896,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

**21. duplicated()**

In [ ]:
import pandas as pd
import os
df = pd.read_csv(r'/content/sample_data/test.csv')
print(df.duplicated().sum())

0

**to drop all duplicated values**

In [ ]:
# df.drop_duplicated(inplace = True)
# print(df.duplicated().sum())